INSERT IGNORE INTO categories (category_type, duration)
VALUES ('AM', 20);
INSERT IGNORE INTO categories (category_type, duration)
VALUES ('A1', 20);
INSERT IGNORE INTO categories (category_type, duration)
VALUES ('A2', 20);
INSERT IGNORE INTO categories (category_type, duration)
VALUES ('A', 20);
INSERT IGNORE INTO categories (category_type, duration)
VALUES ('B1', 20);
INSERT IGNORE INTO categories (category_type, duration)
VALUES ('B', 20);
INSERT IGNORE INTO categories (category_type, duration)
VALUES ('B+E', 20);
INSERT IGNORE INTO categories (category_type, duration)
VALUES ('C', 20);
INSERT IGNORE INTO categories (category_type, duration)
VALUES ('C1', 20);
INSERT IGNORE INTO categories (category_type, duration)
VALUES ('C1+E', 20);
INSERT IGNORE INTO categories (category_type, duration)
VALUES ('C+E', 20);
INSERT IGNORE INTO categories (category_type, duration)
VALUES ('D', 20);
INSERT IGNORE INTO categories (category_type, duration)
VALUES ('D1', 20);
INSERT IGNORE INTO categories (category_type, duration)
VALUES ('D1+E', 20);
INSERT IGNORE INTO categories (category_type, duration)
VALUES ('D+E', 20);
INSERT IGNORE INTO categories (category_type, duration)
VALUES ('T', 20);
INSERT IGNORE INTO categories (category_type, duration)
VALUES ('Tramwaj', 20);